### ISSUE TITLE
Loading chunk failed

### ISSUE THREAD

**Issue by mnpenner** [scinos/webpack-plugin-hash-output#20]
This plugin is causing my JS chunks to not load.

I'm getting errors like,

> Loading chunk 25 failed

Simply removing the plugin makes the problem go away.

Under this plugin, the CSS and JS should have different filenames as I understand it, but that's not what webpack is trying to load:

![image](https://user-images.githubusercontent.com/1112998/41928490-4cb0e8be-792a-11e8-8a9a-334a2b0f6016.png)

I'm using a runtime chunk:

```json
            optimization: {
                minimize: false,
                removeAvailableModules: false,
                runtimeChunk: 'single',
            }
```

I suspect that doesn't play well with this plugin?

Versions, for your reference:

```
❯ yarn list | grep webpack            
├─ extract-text-webpack-plugin@3.0.2
│  └─ webpack-sources@^1.0.1
│  └─ webpack-sources@^1.1.0
├─ uglifyjs-webpack-plugin@1.2.7
│  ├─ webpack-sources@^1.1.0
├─ webpack-addons@1.1.5
├─ webpack-cli@2.1.5
│  ├─ webpack-addons@^1.1.5
├─ webpack-dev-middleware@3.1.3
│  └─ webpack-log@^1.0.1
├─ webpack-dev-server@3.1.4
│  ├─ webpack-dev-middleware@3.1.3
│  ├─ webpack-log@^1.1.2
├─ webpack-log@1.2.0
├─ webpack-plugin-hash-output@3.1.0
├─ webpack-sources@1.1.0
├─ webpack@4.12.1
│  ├─ uglifyjs-webpack-plugin@^1.2.4
│  └─ webpack-sources@^1.0.1
└─ zopfli-webpack-plugin@0.1.0
   └─ webpack-sources@^1.0.1
```

Let me know if there's anything else you need. I'm going to disable this for now.

**Comment by scinos** [comment]
I can't reproduce this problem.

`runtimeChunk` is supported and tested (https://github.com/scinos/webpack-plugin-hash-output/tree/master/test/runtime-chunk), so it should work. I tried with the other two options (`minimize` and `removeAvailableModules`) just to be sure and it still works for me.

I suspect this is caused by `extract-text-webpack-plugin`. Note that this plugin is not compatible with Webpack 4 (see first warning in https://github.com/webpack-contrib/extract-text-webpack-plugin), so I'd suggest to update your config to use https://github.com/webpack-contrib/mini-css-extract-plugin instead.

**Comment by mnpenner** [comment]
I figured out the "CSS ordering issue" -- wasn't an ordering issue at all, it was cssnano changing my z-indexes. Speaking of, I'll try disabling postcss altogether and see if that changes anything...

Nope. Same result. it's not in the entry chunk, but one that's included later at runtime.

The CSS chunk that *does* load appears to be a combined chunk -- the contents appear to be from two different CSS files. I'm not sure what was supposed to be in that JS chunk that's 404ing, but it was something critical to a particular page in my app.

Not sure if that's at all helpful.
